name: Test, build and deploy

on:
  push:
   branches: ["**"]
  pull_request:
    branches: ["**"]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test with unittest
      run: python -m unittest discover -s test/unit/faassupervisor -p '*.py'
  
  pypi:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
        python -m pip install -r requirements.txt
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  build-amd64:
    needs: test
    runs-on: ubuntu-20.04
    container: ghcr.io/grycap/faas-supervisor-build:ubuntu16.04-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build binary
      run: |
        pyinstaller --onefile -n supervisor-bin faassupervisor/supervisor.py
        pyinstaller faassupervisor/supervisor.py
        cd dist
        zip -r supervisor.zip supervisor
        rm -r supervisor
        mv supervisor-bin supervisor
    - name: Upload amd64 binary
      uses: actions/upload-artifact@v2
      with:
        name: supervisor
        path: dist/supervisor
    - name: Upload amd64 zip
      uses: actions/upload-artifact@v2
      with:
        name: supervisor.zip
        path: dist/supervisor.zip

  build-alpine-amd64:
    needs: test
    runs-on: ubuntu-20.04
    container: ghcr.io/grycap/faas-supervisor-build:alpine-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build binary
      run: |
        pyinstaller --onefile -n supervisor-bin faassupervisor/supervisor.py
        pyinstaller faassupervisor/supervisor.py
        cd dist
        zip -r supervisor-alpine.zip supervisor
        rm -r supervisor
        mv supervisor-bin supervisor-alpine
    - name: Upload amd64 binary
      uses: actions/upload-artifact@v2
      with:
        name: supervisor-alpine
        path: dist/supervisor-alpine
    - name: Upload amd64 zip
      uses: actions/upload-artifact@v2
      with:
        name: supervisor-alpine.zip
        path: dist/supervisor-alpine.zip

  build-aarch64:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build binary on emulated aarch64
      uses: uraimo/run-on-arch-action@v2.0.7
      with:
        arch: aarch64
        distro: ubuntu16.04
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        dockerRunArgs: |
          --volume  "${PWD}:/repo"
        shell: /bin/sh
        install: |
          apt update
          apt install -y zip build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
          wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
          tar -xzf Python-3.8.12.tgz
          cd Python-3.8.12
          ./configure --enable-optimizations --enable-shared
          make altinstall
          export LD_LIBRARY_PATH=/usr/local/lib
          cd ..
          wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-aarch64.sh
          chmod +x cmake-3.22.1-linux-aarch64.sh
          mkdir /opt/cmake
          ./cmake-3.22.1-linux-aarch64.sh --skip-license --exclude-subdir --prefix=/opt/cmake
          ln -s /opt/cmake/bin/* /usr/local/bin
          python3.8 -m ensurepip
          python3.8 -m pip install pyinstaller
        run: |
          cd /repo
          export LD_LIBRARY_PATH=/usr/local/lib
          python3.8 -m pip install -r requirements.txt
          pyinstaller --onefile -n supervisor-arm64 faassupervisor/supervisor.py
          pyinstaller faassupervisor/supervisor.py
          cd dist
          zip -r supervisor-arm64.zip supervisor
    - name: Upload arm64 binary
      uses: actions/upload-artifact@v2
      with:
        name: supervisor-arm64
        path: dist/supervisor-arm64
    - name: Upload arm64 zip
      uses: actions/upload-artifact@v2
      with:
        name: supervisor-arm64.zip
        path: dist/supervisor-arm64.zip

  release-assets:
    needs:
    - build-amd64
    - build-aarch64
    - build-alpine-amd64
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:
    - name: Download jobs' artifacts
      uses: actions/download-artifact@v2
    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          supervisor.zip/supervisor.zip
          supervisor/supervisor
          supervisor-arm64/supervisor-arm64
          supervisor-arm64.zip/supervisor-arm64.zip
          supervisor-alpine.zip/supervisor-alpine.zip
          supervisor-alpine/supervisor-alpine
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}