name: Test, build and deploy

on:
  push:
   branches: ["**"]
  pull_request:
    branches: ["**"]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test with unittest
      run: python -m unittest discover -s test/unit/faassupervisor -p '*.py'
  
  pypi:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
        python -m pip install -r requirements.txt
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  build-amd64:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
        apt update
        apt install -y zip
    - name: Build binary
      run: |
        pyinstaller --onefile -n supervisor faassupervisor/supervisor.py
        pyinstaller faassupervisor/supervisor.py
        cd dist
        zip -r supervisor.zip supervisor
    - name: Deploy to release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/supervisor
          dist/supervisor.zip

  build-aarch64:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build binary on emulated aarch64
      uses: uraimo/run-on-arch-action@v2.0.7
      with:
        arch: aarch64
        distro: ubuntu18.04
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        dockerRunArgs: |
          --volume  "${PWD}:/repo"
        shell: /bin/sh
        install: |
          apt update
          apt install -y software-properties-common build-essential zlib1g-dev
          add-apt-repository -y ppa:deadsnakes/ppa
          apt update
          apt install -y python3.8-dev python3.8-venv zip
          python3.8 -m ensurepip
          python3.8 -m pip install pyinstaller
        run: |
          cd /repo
          python3.8 -m pip install -r requirements.txt
          pyinstaller --onefile -n supervisor-arm64 faassupervisor/supervisor.py
          pyinstaller faassupervisor/supervisor.py
          cd dist
          zip -r supervisor-arm64.zip supervisor
    - name: Deploy to release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/supervisor-arm64
          dist/supervisor-arm64.zip